server:
  port: 8520
spring:
  servlet:
    ​multipart:
      file-size-threshold: 100MB
      max-request-size: 100MB
      max-file-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: redis.dev-marketgo.com
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.dev-marketgo.com:3306/marketgo?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: MarketGo@mysql2022
  jpa:
    hibernate:
      ddl: update
    show-sql: true
  rabbitmq:
    host: rabbitmq.dev-marketgo.com #ip
    port: 5672 #端口
    username: admin #用户名
    password: admin #密码
    virtual-host: /wecom #虚拟机名称
    # 开启消息确认机制 confirm 异步
    publisher-confirm-type: correlated
    publisher-returns: true #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1  #当前监听容器数
        max-concurrency: 1 #最大数
        retry:
          enabled: true
xxl:
  job:
    admin:
      # 调度中心部署跟地址[选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://xxl-job.dev-marketgo.com:8580/xxl-job-admin
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: marketgo-job
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: xxl-job.dev-marketgo.com
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath:
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      logretentiondays: 30
    accessToken: default_token


